spring:
  profiles:
    include: dev
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${client-id-kakao}
            client-secret: ${client-secret-kakao}
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
              - profile_image
            redirect-uri: ${base-url}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
          naver:
            client-name: naver
            client-id: ${client-id-naver}
            client-secret: ${client-secret-naver}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${base-url}/login/oauth2/code/naver
            scope:
              - name
              - email
              - profile_image
          google:
            client-name: google
            client-id: ${client-id-google}
            client-secret: ${client-secret-google}
            scope:
              - profile
              - email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          #            jwk-set-uri:
          #            issuer-uri:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mvc:
    hiddenmethod:
      filter:
        enabled: true

jwt:
  secret-key: ${jwt-secret}
  access-token-validity-in-sec: 1800 # 30분
  refresh-token-validity-in-sec: 86400 #

server:
  port: 8080
  tomcat:
    use-relative-redirects: true
