name: CI/CD using Github Actions & AWS CodeDeploy

on:
  pull_request:
    branches:
      - main

#permissions:
#  contents: read
defaults:
  run:
    working-directory: the-last-is-me
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: grant execute permission for gradlew
        run : chmod +x gradlew

      - name: gradle build
        run: ./gradlew build

      - name: publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: the-last-is-me/build/test-results/test/TEST-*.xml

      - name: add comments to a pull request
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: the-last-is-me/build/test-results/test/TEST-*.xml
