name: CI/CD using Github Actions & AWS CodeDeploy

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
#permissions:
#  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set application.yaml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yaml
        env:
          spring.profiles.include: prod
          spring.security.oauth2.client.registration.kakao.client-id: ${{ secrets.CLIENT_ID_KAKAO }}
          spring.security.oauth2.client.registration.kakao.client-secret: ${{ secrets.CLIENT_SECRET_KAKAO }}
          spring.security.oauth2.client.registration.kakao.redirect-uri: ${{ secrets.REDIRECT_URI_KAKAO }}
          spring.security.oauth2.client.registration.google.client-id: ${{ secrets.CLIENT_ID_GOOGLE }}
          spring.security.oauth2.client.registration.google.client-secret: ${{ secrets.CLIENT_SECRET_GOOGLE }}
          spring.security.oauth2.client.registration.naver.client-id: ${{ secrets.CLIENT_ID_NAVER }}
          spring.security.oauth2.client.registration.naver.client-secret: ${{ secrets.CLIENT_SECRET_NAVER }}
          spring.security.oauth2.client.registration.naver.redirect-uri: ${{ secrets.REDIRECT_URI_NAVER }}
          jwt.secret-key: ${{ secrets.JWT_SECRET }}

      - name: Set application-prod.yaml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application-prod.yaml
        env:
          spring.datasource.url: ${{ secrets.PROD_DB_URL }}
          spring.datasource.username: ${{ secrets.PROD_DB_USERNAME }}
          spring.datasource.password: ${{ secrets.PROD_DB_PASSWORD }}

      - name: GRANT execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradle build
        run: ./gradlew build

      - name: publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/test/TEST-*.xml

      - name: add comments to a pull request
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: build/test-results/test/TEST-*.xml
